import { ComplianceAlert, AlertType, Severity, Status } from './types';

const alertTypes: AlertType[] = [
  'Market Manipulation',
  'Wash Trading',
  'Spoofing',
  'Insider Trading',
  'Position Limit Breach',
];

const severities: Severity[] = ['Critical', 'High', 'Medium', 'Low'];
const statuses: Status[] = ['New', 'In Review', 'Escalated', 'Dismissed', 'Resolved'];

const traderNames = [
  'James Mitchell', 'Sarah Chen', 'Michael Rodriguez', 'Emily Johnson',
  'David Kim', 'Lisa Anderson', 'Robert Taylor', 'Jennifer Martinez',
  'William Brown', 'Amanda White', 'Christopher Lee', 'Jessica Davis',
  'Daniel Wilson', 'Nicole Garcia', 'Matthew Moore', 'Ashley Thompson',
  'Andrew Jackson', 'Stephanie Harris', 'Kevin Clark', 'Rachel Lewis',
];

const firms = [
  'Goldman Sachs', 'Morgan Stanley', 'JPMorgan Chase', 'Bank of America',
  'Citigroup', 'Deutsche Bank', 'Barclays', 'Credit Suisse',
  'UBS', 'Wells Fargo', 'BNP Paribas', 'HSBC',
];

const descriptions = [
  'Unusual trading pattern detected with rapid buy/sell orders in short time window',
  'Multiple accounts showing coordinated trading behavior across different instruments',
  'Large order placement followed by immediate cancellation pattern observed',
  'Trading activity detected prior to material non-public information release',
  'Position size exceeds regulatory limits for the given instrument category',
  'Suspicious volume spike coinciding with price movement in illiquid market',
  'Cross-market arbitrage pattern suggesting potential manipulation',
  'Repeated pattern of order book manipulation detected via algorithmic analysis',
  'Trader activity shows correlation with insider information timeline',
  'Position concentration risk exceeds multiple regulatory thresholds',
];

function randomDate(start: Date, end: Date): string {
  const date = new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  return date.toISOString();
}

function generateTimeline(alertId: string, status: Status): Array<{ id: string; timestamp: string; action: string; user: string; notes?: string }> {
  const timeline = [
    {
      id: `${alertId}-1`,
      timestamp: randomDate(new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
      action: 'Alert Created',
      user: 'Automated System',
      notes: 'Alert generated by compliance monitoring system',
    },
  ];

  if (status !== 'New') {
    timeline.push({
      id: `${alertId}-2`,
      timestamp: randomDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), new Date()),
      action: 'Investigation Started',
      user: 'John Smith',
      notes: 'Initial review initiated',
    });
  }

  if (status === 'Escalated') {
    timeline.push({
      id: `${alertId}-3`,
      timestamp: randomDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), new Date()),
      action: 'Escalated',
      user: 'Jane Doe',
      notes: 'Escalated to senior compliance officer',
    });
  }

  if (status === 'Resolved' || status === 'Dismissed') {
    timeline.push({
      id: `${alertId}-4`,
      timestamp: randomDate(new Date(Date.now() - 12 * 60 * 60 * 1000), new Date()),
      action: status === 'Resolved' ? 'Resolved' : 'Dismissed',
      user: 'John Smith',
      notes: status === 'Resolved' ? 'Issue resolved after investigation' : 'False positive - dismissed',
    });
  }

  return timeline.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
}

export function generateMockAlerts(): ComplianceAlert[] {
  const alerts: ComplianceAlert[] = [];
  const now = new Date();
  const startDate = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000); // 30 days ago

  for (let i = 0; i < 20; i++) {
    const traderIndex = i % traderNames.length;
    const traderName = traderNames[traderIndex];
    const traderId = `TRD${String(traderIndex + 1).padStart(4, '0')}`;
    
    const type = alertTypes[Math.floor(Math.random() * alertTypes.length)];
    const severity = severities[Math.floor(Math.random() * severities.length)];
    const status = statuses[Math.floor(Math.random() * statuses.length)];
    
    const alertId = `ALT${String(i + 1).padStart(6, '0')}`;
    const timeline = generateTimeline(alertId, status);

    alerts.push({
      id: alertId,
      type,
      severity,
      status,
      trader: {
        id: traderId,
        name: traderName,
        email: `${traderName.toLowerCase().replace(' ', '.')}@${firms[Math.floor(Math.random() * firms.length)].toLowerCase().replace(/\s+/g, '')}.com`,
        firm: firms[Math.floor(Math.random() * firms.length)],
        registrationDate: randomDate(new Date(2018, 0, 1), new Date(2022, 11, 31)),
      },
      timestamp: randomDate(startDate, now),
      description: descriptions[Math.floor(Math.random() * descriptions.length)],
      detectedBy: 'Automated Compliance System v3.2',
      investigationNotes: status !== 'New' ? 'Initial investigation notes: Reviewing trading patterns and order history. Cross-referencing with market data and regulatory thresholds.' : '',
      timeline,
    });
  }

  return alerts.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
}

